// SPDX-License-Identifier: MIT
pragma solidity ^0.8.26;

import "./V4.sol";

// =============================================================================
// PROVIDED. You do not edit this file and you do not submit it.
//
// Every task contract inherits from this. It holds the addresses and the pool
// settings you typed in when you deployed, and it works out the pool key for you.
// =============================================================================

abstract contract ExamBase {
    using PoolIdLibrary for PoolKey;
    using PoolState for IPoolManager;

    IPoolManager public immutable poolManager;

    /// @notice Your token A and token B, exactly as you deployed them in Task 1.
    address public immutable tokenA;
    address public immutable tokenB;

    /// @notice The fee tier and tick spacing from your parameter sheet.
    uint24 public immutable FEE;
    int24 public immutable TICK_SPACING;

    constructor(address _poolManager, address _tokenA, address _tokenB, uint24 _fee, int24 _tickSpacing) {
        require(_poolManager != address(0), "pool manager address is empty");
        require(_tokenA != address(0) && _tokenB != address(0), "token address is empty");
        require(_tokenA != _tokenB, "token A and token B are the same address");
        require(_tickSpacing > 0, "tick spacing must be positive");

        poolManager = IPoolManager(_poolManager);
        tokenA = _tokenA;
        tokenB = _tokenB;
        FEE = _fee;
        TICK_SPACING = _tickSpacing;
    }

    /// @notice The pool sorts the two currencies by address. This tells you which way it went.
    function alphaIsCurrency0() public view returns (bool) {
        return tokenA < tokenB;
    }

    /// @notice The lower of your two token addresses.
    function currency0() public view returns (address) {
        return alphaIsCurrency0() ? tokenA : tokenB;
    }

    /// @notice The higher of your two token addresses.
    function currency1() public view returns (address) {
        return alphaIsCurrency0() ? tokenB : tokenA;
    }

    /// @notice The four fields that identify your pool, plus the hooks address.
    function poolKey() public view returns (PoolKey memory) {
        return PoolKey({
            currency0: Currency.wrap(currency0()),
            currency1: Currency.wrap(currency1()),
            fee: FEE,
            tickSpacing: TICK_SPACING,
            hooks: IHooks(address(0))
        });
    }

    /// @notice The unique id of your pool.
    function poolId() public view returns (bytes32) {
        return PoolId.unwrap(poolKey().toId());
    }

    /// @notice The live price and tick of your pool. Both are zero before the pool is opened.
    function currentSlot0() public view returns (uint160 sqrtPriceX96, int24 tick) {
        (sqrtPriceX96, tick,,) = poolManager.getSlot0(poolKey().toId());
    }

    /// @notice The live tick of your pool.
    function currentTick() public view returns (int24 tick) {
        (, tick) = currentSlot0();
    }

    /// @notice False until Task 2 has opened the pool.
    function poolExists() public view returns (bool) {
        (uint160 sqrtPriceX96,) = currentSlot0();
        return sqrtPriceX96 != 0;
    }
}
